version: '3.6'

services:
  eureka:
    image: springio/eureka:0.0.1-SNAPSHOT
    container_name: eureka
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka"]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway:
    image: springio/gateway:0.0.1-SNAPSHOT
    container_name: gateway
    depends_on:
      - eureka
    ports:
      - 8888:8888
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka

  beers:
    image: springio/beers:0.0.1-SNAPSHOT
    container_name: beers
    depends_on:
      - eureka
    ports:
      - 8000:8000
    links:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka

  beers2:
    image: springio/beers:0.0.1-SNAPSHOT
    container_name: beers2
    depends_on:
      - eureka
    ports:
      - 8001:8000
    links:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka

  beers3:
    image: springio/beers:0.0.1-SNAPSHOT
    container_name: beers3
    depends_on:
      - eureka
    ports:
      - 8002:8000
    links:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
