spring:
  cloud:
    gateway:
      routes:
        - predicates:
            - Path=/beers/**
          filters:
            - StripPrefix=1
          uri: "http://localhost:8000/beers"
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka