server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: beer-service
          uri: 'lb://beer-service'
          predicates:
            - Path=/beers/**
          filters:
          - StripPrefix=1
          - name: RequestRateLimiter
            args:
              key-resolver: "#{@testResolver}"
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 5

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
